### ISSUE TITLE
search crashes the whole program

### ISSUE THREAD

**Issue by guanqun** [chzyer/readline#30]
It's the cockroach project that uses your readline library, but when I tried to back search (using Ctrl+R), it just crashes, the backtrace is as follows:

Please help fix this. Thanks!

```
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:15432> panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xb8 pc=0x42e0c96]

goroutine 12 [running]:
github.com/chzyer/readline.(*opSearch).SearchRefresh(0xc8202925b0, 0xd)
	/Users/q/go/src/github.com/chzyer/readline/search.go:127 +0xc6
github.com/chzyer/readline.(*opSearch).SearchMode(0xc8202925b0, 0x0)
	/Users/q/go/src/github.com/chzyer/readline/search.go:100 +0x78
github.com/chzyer/readline.(*Operation).ioloop(0xc820261440)
	/Users/q/go/src/github.com/chzyer/readline/operation.go:140 +0x2112
created by github.com/chzyer/readline.NewOperation
	/Users/q/go/src/github.com/chzyer/readline/operation.go:70 +0x428

goroutine 1 [select]:
github.com/chzyer/readline.(*Operation).Runes(0xc820261440, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/q/go/src/github.com/chzyer/readline/operation.go:316 +0x2d5
github.com/chzyer/readline.(*Operation).String(0xc820261440, 0x0, 0x0, 0x0, 0x0)
	/Users/q/go/src/github.com/chzyer/readline/operation.go:300 +0x40
github.com/chzyer/readline.(*Instance).Readline(0xc82027ed80, 0x0, 0x0, 0x0, 0x0)
	/Users/q/go/src/github.com/chzyer/readline/readline.go:184 +0x3d
github.com/chzyer/readline.Line(0xc82028d700, 0xd, 0x0, 0x0, 0x0, 0x0)
	/Users/q/go/src/github.com/chzyer/readline/std.go:44 +0xf6
github.com/cockroachdb/cockroach/cli.runInteractive(0xc8202943c0, 0xc820205e60, 0x28, 0x0, 0x0)
	/Users/q/go/src/github.com/cockroachdb/cockroach/cli/sql.go:173 +0x450
github.com/cockroachdb/cockroach/cli.runTerm(0x5c13320, 0xc82028d600, 0x0, 0x1, 0x0, 0x0)
	/Users/q/go/src/github.com/cockroachdb/cockroach/cli/sql.go:271 +0x151
github.com/spf13/cobra.(*Command).execute(0x5c13320, 0xc82028d5a0, 0x1, 0x1, 0x0, 0x0)
	/Users/q/go/src/github.com/spf13/cobra/command.go:565 +0x63b
github.com/spf13/cobra.(*Command).ExecuteC(0x5c10320, 0x5c13320, 0x0, 0x0)
	/Users/q/go/src/github.com/spf13/cobra/command.go:656 +0x56b
github.com/spf13/cobra.(*Command).Execute(0x5c10320, 0x0, 0x0)
	/Users/q/go/src/github.com/spf13/cobra/command.go:615 +0x2d
github.com/cockroachdb/cockroach/cli.Run(0xc82000a190, 0x2, 0x2, 0x0, 0x0)
	/Users/q/go/src/github.com/cockroachdb/cockroach/cli/cli.go:85 +0x7c
main.main()
	/Users/q/go/src/github.com/cockroachdb/cockroach/main.go:37 +0xe6

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1

goroutine 7 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x5c23740)
	/Users/q/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1030 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/Users/q/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:610 +0xbc

goroutine 9 [syscall]:
os/signal.loop()
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/Cellar/go/1.5.3/libexec/src/os/signal/signal_unix.go:28 +0x37

goroutine 10 [chan receive]:
database/sql.(*DB).connectionOpener(0xc8202943c0)
	/usr/local/Cellar/go/1.5.3/libexec/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/Cellar/go/1.5.3/libexec/src/database/sql/sql.go:481 +0x336

goroutine 11 [syscall]:
syscall.Syscall(0x3, 0x0, 0xc8202ac000, 0x1000, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x0, 0xc8202ac000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/syscall/zsyscall_darwin_amd64.go:972 +0x5f
syscall.Read(0x0, 0xc8202ac000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc82002c008, 0xc8202ac000, 0x1000, 0x1000, 0xc8202612b8, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/os/file_unix.go:211 +0x75
os.(*File).Read(0xc82002c008, 0xc8202ac000, 0x1000, 0x1000, 0x1, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/os/file.go:95 +0x8a
bufio.(*Reader).fill(0xc82002be70)
	/usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadRune(0xc82002be70, 0xc820261260, 0xc82002bddc, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/bufio/bufio.go:260 +0xc8
github.com/chzyer/readline.(*Terminal).ioloop(0xc8202904b0)
	/Users/q/go/src/github.com/chzyer/readline/terminal.go:111 +0x24b
created by github.com/chzyer/readline.NewTerminal
	/Users/q/go/src/github.com/chzyer/readline/terminal.go:34 +0x189
```

**Comment by chzyer** [comment]
I had fixed this, sorry about that. I will add more test later.

**Comment by chzyer** [comment]
Please send a PR to cockroach, thanks!

**Comment by guanqun** [comment]
Thank you for your quick fix! @chzyer I'll send a PR to cockroach.
